name: Preview Deploy (PR)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]
concurrency:
  group: railway-preview-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Create/Update Preview Deployment
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --detach
          echo "Preview deploy triggered. Check Railway for the PR environment."
