name: Deploy to Railway
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
concurrency:
  group: railway-deploy-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Node (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Deploy with Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ vars.RAILWAY_SERVICE_ID }}
        run: |
          if [ -n "$RAILWAY_SERVICE_ID" ]; then
            railway up --service "$RAILWAY_SERVICE_ID"
          else
            railway up
          fi
